set(SRC_FILES
    App.cpp
    AppAudio.cpp
    AppGoal.cpp
    AppLevel.cpp
    AppLifecycle.cpp
    AppRender.cpp
    AppUi.cpp
    AppUpdate.cpp
    GameImage.cpp
    GameTexture.cpp
    DebugManager.cpp
    Mario.cpp
    MarioAnimation.cpp
    MarioGoal.cpp
    MarioPower.cpp
    MarioUpdate.cpp
    Enemy.cpp
    EnemyCombat.cpp
    EnemyUpdate.cpp
    Fireball.cpp
    Debris.cpp
    Pickup.cpp
    ConvertSketch.cpp
    ConvertSketchDetail.cpp
)

set(INCLUDE_FILES
    App.hpp
    AppDetail.hpp
    DebugManager.hpp
    Mario.hpp
    MarioDetail.hpp
    Animation.hpp
    Enemy.hpp
    EnemyDetail.hpp
    Fireball.hpp
    GameImage.hpp
    GameTexture.hpp
    Debris.hpp
    Pickup.hpp
    ConvertSketch.hpp
    ConvertSketchDetail.hpp
    MapManager.hpp
)

set(TEST_FILES
)
